<?php
/**
 * Implementation of hook_init().
 */

function asc_giveto_counter_menu() {
  drupal_add_js(drupal_get_path('module', 'asc_giveto_counter') . '/asc_giveto_counter.js');
  drupal_add_js(drupal_get_path('module', 'asc_giveto_counter') . '/jquery.jodometer.js');
  drupal_add_css(drupal_get_path('module', 'asc_giveto_counter') . '/asc_giveto_counter.css', array('group' => CSS_DEFAULT, 'type' => 'file'));
}
?>
