<?php
/**
 * Implementation of hook_init().
 */

function asc_giveto_counter_init() {
  drupal_add_js(drupal_get_path('module', 'asc_giveto_counter') . '/asc_giveto_counter.js');
  drupal_add_js(drupal_get_path('module', 'asc_giveto_counter') . '/jquery.jodometer.js');
  drupal_add_css(drupal_get_path('module', 'asc_giveto_counter') . '/asc_giveto_counter.css');
}

function asc_giveto_counter_cron() {
  $contents = drupal_http_request('http://www.osu.edu/giving/feeds/gift-amount.js');
  preg_match("/\d+/", $contents->data, $amount);
  variable_set('asc_giveto_counter_amount', $amount[0]);
  watchdog('opic', 'Giveto Counter Updated');
}
